apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solar-system
metadata:
  name: arbitrary
generatorOptions:
  disableNameSuffixHash: true
# generate secret only first time
secretGenerator:
  - name: solar-system-regcred
    files:
      - .dockerconfigjson=01dockerconfig.json
    type: kubernetes.io/dockerconfigjson
commonLabels:
  app: solar-system
resources:
  - 00namespace.yaml
  - 02serviceAccount.yaml
  - 03deployment.yaml
  - 04service.yaml
  - 11issuer.yaml
  - 12certificate.yaml
  - 13middleWare.yaml
  - 14ingressRouter.yaml
  